### ISSUE TITLE
Timestamp usage

### ISSUE THREAD

**Issue by pauliax** [RewardsNetwork/Alloy-ICO-Contracts#5]
There’s a problem with using timestamps and now (alias for block.timestamp) for contract logic, based on the fact that miners can perform some manipulation. In general, it’s better not to rely on timestamps for contract logic. The solution is to use block.number instead, and approximate dates with expected block heights and time periods with expected block amounts.

**Comment by pauliax** [comment]
This issue is no longer relevant as according to the latest OpenZeppelin reccomendation:
"The current recommendation is to use timestamps instead. The risk of miner manipulation of timestamps is very low for this use case, and due to the Difficulty Bomb it is now very difficult to correctly estimate future block times. Consider switching to timestamps."
More: https://blog.zeppelin.solutions/global-messaging-token-audit-865e6a821cd8

**Comment by shoaib-dr** [comment]
Thanks. Closing the issue.
